// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from "./DatabaseTypes";

function readEnv() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
    (typeof import.meta !== "undefined" && (import.meta as ImportMeta).env?.VITE_SUPABASE_URL) ||
    (typeof process !== "undefined" ? process.env?.SUPABASE_URL : undefined);
  const SUPABASE_PUBLISHABLE_KEY =
    (typeof import.meta !== "undefined" && (import.meta as ImportMeta).env?.VITE_SUPABASE_PUBLISHABLE_KEY) ||
    (typeof process !== "undefined" ? process.env?.SUPABASE_PUBLISHABLE_KEY : undefined);
  return { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY };
}

export function isSupabaseConfigured(): boolean {
  const { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } = readEnv();
  return !!(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
}

let warned = false;
function warnOnce() {
  if (warned) return;
  warned = true;
  console.warn(
    "[Supabase] Missing VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY. " +
      "Running in offline shell mode — auth and data calls will no-op. " +
      "Connect Lovable Cloud or set the variables in .env to enable backend features.",
  );
}

/** A non-throwing stub that satisfies the small subset of the supabase-js
 *  surface our shell uses at startup. All reads resolve to "no data" and all
 *  writes return a friendly error instead of crashing the app. */
function createStubClient(): SupabaseClient<Database> {
  const offlineError = new Error("Backend not configured (Supabase env missing).");
  const authStub = {
    getUser: async () => ({ data: { user: null }, error: null }),
    getSession: async () => ({ data: { session: null }, error: null }),
    onAuthStateChange: (_cb: unknown) => ({
      data: { subscription: { unsubscribe() {} } },
    }),
    signOut: async () => ({ error: null }),
    signInWithPassword: async () => ({ data: { user: null, session: null }, error: offlineError }),
    signUp: async () => ({ data: { user: null, session: null }, error: offlineError }),
    signInWithOtp: async () => ({ data: { user: null, session: null }, error: offlineError }),
    signInWithOAuth: async () => ({ data: { provider: null, url: null }, error: offlineError }),
    resetPasswordForEmail: async () => ({ data: {}, error: offlineError }),
    updateUser: async () => ({ data: { user: null }, error: offlineError }),
    setSession: async () => ({ data: { user: null, session: null }, error: offlineError }),
    refreshSession: async () => ({ data: { user: null, session: null }, error: offlineError }),
    exchangeCodeForSession: async () => ({ data: { user: null, session: null }, error: offlineError }),
  };
  const queryStub: any = new Proxy(
    Promise.resolve({ data: null, error: offlineError }),
    {
      get(target, prop) {
        if (prop === "then" || prop === "catch" || prop === "finally") {
          return (target as any)[prop].bind(target);
        }
        return () => queryStub;
      },
    },
  );
  const storageBucket = {
    upload: async () => ({ data: null, error: offlineError }),
    download: async () => ({ data: null, error: offlineError }),
    remove: async () => ({ data: null, error: offlineError }),
    list: async () => ({ data: [], error: null }),
    createSignedUrl: async () => ({ data: null, error: offlineError }),
    getPublicUrl: () => ({ data: { publicUrl: "" } }),
  };
  const channelStub = {
    on: () => channelStub,
    subscribe: () => channelStub,
    unsubscribe: async () => "ok",
  };
  const client = {
    auth: authStub,
    from: () => queryStub,
    rpc: async () => ({ data: null, error: offlineError }),
    storage: { from: () => storageBucket },
    channel: () => channelStub,
    removeChannel: async () => "ok",
    functions: { invoke: async () => ({ data: null, error: offlineError }) },
  } as unknown as SupabaseClient<Database>;
  return client;
}

function createRealClient(): SupabaseClient<Database> {
  const { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } = readEnv();
  return createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: SupabaseClient<Database> | undefined;

function getClient(): SupabaseClient<Database> {
  if (_supabase) return _supabase;
  if (!isSupabaseConfigured()) {
    warnOnce();
    _supabase = createStubClient();
  } else {
    _supabase = createRealClient();
  }
  return _supabase;
}

// Import the supabase client like this:
// import { supabase } from "@backend/database/SupabaseClient";
export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_, prop, receiver) {
    return Reflect.get(getClient(), prop, receiver);
  },
});
